title: "Oscar Bocanegra | Data Engineer & AI Specialist"
author: "Oscar Giovanni Bocanegra"
email: "oscargiovanni@gmail.com"
description: "Portafolio profesional de Oscar Bocanegra, especialista en Data Engineering e Inteligencia Artificial con amplia experiencia en soluciones empresariales."

github_username: oscargbocanegra
linkedin_username: oscargbocanegra
twitter_username: oscargbocanegra

url: "https://oscargbocanegra.github.io"
baseurl: ""

plugins:
  - jekyll-sitemap
